# Generated by Django 5.0.2 on 2024-02-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_address_alter_author_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.IntegerField(max_length=10),
        ),
    ]
